import { createI18n } from 'vue-i18n';

const messages = {
    en: {
      portaltitle: "Saint \nSophia's\nInscriptions",
      etruscanabout: "The portal is published by GRIDH at the university of Gothenburg in close collaboration with the Swedish Institute in Rome.",
      documentation: "Documentation by category",
      timeperiod: "Time period",
      tag: "Tag",
      typeofdata: "Type of data",
      typeofinscription: "Type of inscription",
      dataset: "Dataset",
      searchpanels: "Search for a panel or inscription",
      inscriptions: "Inscriptions",
      alllanguages: "All languages",
      text: "Text",
      texts: "Texts",
      figure: "Figure",
      figures: "Figures",
      language: "Language",
      composite: "Composite",
      composites: "Composites",
      panels: "Panels",
      room: "Room",
      plan: "Plan",
      plans: "Plans",
      groundfloor: "Ground floor",
      secondfloor: "Second floor",
      languages: "Languages",
      map: "map",
      gallery: "gallery",
      infobutton: "About the portal",
      languagebutton: "Українською",
      moreinfo: "More Info",
      threedmodel: "3D Model",
      threedmodels: "3D models",
      panelsshown: "Panels shown",
      panelshidden: "Panels hidden",
      photographs: "Photographs",
      plans: "Plans",
      type: "Type",
      period: "Period",
      aboutportalmain:"",
      aboutportal: "",
      explore: "Explore",  
      documents: "Documents",
      sortbytype: "Sort by: TYPE",
      sortbyyear: "Sort by: YEAR",
      size: "Size",
      published: "Published",
      editplace: "Edit place",
      nophoto: "No photographs available",
      drawings: "Drawings",
      showall: "Show all",
      alldatasets: "All datasets",
      "categories": {
        "all": "All types",
        "drawings": "Drawings",
        "models": "3D models"
      },
    },

    uk: {
      portaltitle: "Написи \nСвятої \nСофії",
      etruscanabout: "The portal is published by GRIDH at the university of Gothenburg in close collaboration with the Swedish Institute in Rome.",
      documentation: "Documentation by category",
      timeperiod: "Time period",
      tag: "Tag",
      typeofdata: "Type of data",
      typeofinscription: "Вид напису",
      dataset: "Dataset",
      searchpanels: "Шукайте панно або напис",
      inscriptions: "Hаписи",
      alllanguages: "Всі мови",
      text: "Текст",
      texts: "Тексти",
      figure: "Mалюнок",
      figures: "Цифри",
      language: "Мова напису",
      composite: "CКомпозитний",
      composites: "композити",
      panels: "Панелі",
      room: "Кімната",
      plan: "План",
      plans: "Плани",
      groundfloor: "Перший поверх",
      secondfloor: "Другий поверх",
      languages: "Мови",
      map: "map",
      gallery: "gallery",
      infobutton: "Про портал",
      languagebutton: "In English",
      moreinfo: "Більше інформації",
      threedmodel: "3D Model",
      threedmodels: "3D models",
      panelsshown: "Показані панелі",
      panelshidden: "Панелі приховані",
      photographs: "Photographs",
      plans: "Плани",
      type: "Type",
      period: "Period",
      aboutportalmain:"",
      aboutportal: "",
      explore: "Explore",  
      documents: "Documents",
      sortbytype: "Sort by: TYPE",
      sortbyyear: "Sort by: YEAR",
      size: "Size",
      published: "Published",
      editplace: "Edit place",
      nophoto: "No photographs available",
      drawings: "Drawings",
      showall: "Show all",
      alldatasets: "All datasets",
      "categories": {
        "all": "Всі види",
        "drawings": "Drawings",
        "models": "3D models"
      },
    },
};  

const i18n = createI18n({
  locale: 'en', 
  messages,
});

export default i18n;
